### ISSUE TITLE
New params and urls

### ISSUE THREAD

**Issue by crinny** [Zeroeh/RotMG-Appspot#12]
Too lazy to make a Pull Request xD
`/playerProductInstall.swf`
`/UGDTermsofUse.html`
`kongregate.html`
**Testing servers**: https://test2.realmofthemadgod.com, https://rotmgtesting3.appspot.com, https://testing.realmofthemadgod.com, https://test.realmofthemadgod.com (admin-only)
![изображение](https://user-images.githubusercontent.com/42045258/58866435-453dd100-86c1-11e9-88d0-646ecafba671.png)
Also some images, should we include them? https://realmofthemadgodhrd.appspot.com/images/backgroundPattern.png, https://realmofthemadgodhrd.appspot.com/images/playButton.png, https://realmofthemadgodhrd.appspot.com/images/downloadButton.png, https://realmofthemadgodhrd.appspot.com/images/Logo_Deca.png

`steamworks/finalizePurchase` ->appid, orderid, authorized (1 or 0)
`kabam/verify` -> kabamemail, kabampassword
`credits/kabamadd` -> naid, signedRequest, createdat
`kabam/getcredentials` -> signedRequest, entrytag
`kongregate/internalRegister` -> userId, username, gameAuthToken, guid
`credits/token` -> guid, password
`credits/add` -> tok, exp, guid, provider, jwt, price, paymentid
`credits/pwpurchase` -> iframeUrl (json with these params: token, production)
`picture/get` -> id, time
`picture/save`
`package/getPackages` -> language, version
`char/list` -> challenger (true or false)
`char/delete` -> charId **is** always 1
![reason](https://user-images.githubusercontent.com/42045258/58413585-d7225a00-8081-11e9-88af-9260937eb62c.png)
`account/changeEmail` -> guid, password, newGuid
`dailyquest/resetDailyQuestsAdmin` -> guid, password (requires admin account)
`account/isEmailVerified` -> guid, password
`clientError/add` -> text, guid
text =
```
Build:RotMG #31.8.2
message:
stackTrace:
Some debug info that can be found in client: `com/company/util/CapabilitiesUtil.as`
```
`dailyquest/resetDailyQuests` now returns `<Error>Server error<Error/>`
`mysterybox/getBoxes` -> guid, password, version (seems to accept any float like 1.0)
`account/playFortuneGame` -> choice, status, currency (2 for fortune tokens or 0 for gold)
`account/purchaseSkin` -> guid, password, skinType
`char/purchaseClassUnlock` -> guid, password, game_net_user_id, game_net, play_platform, do_login, classType
`kabam/link` -> kabamemail, kabampassword, email, password
`migrate/doMigration` -> guid, password
`migrate/userAccountReset` -> guid, password
`steamworks/purchaseOffer` -> steamid, data
`kongregate/register` -> userId, username, gameAuthToken, newGUID, newPassword, entrytag
`ugc/save` -> guid, password, name, description, width, height, mapjm, tags, totalObjects, totalTiles, thumbnail, overwrite (on or off) (seems to always return `<Error>Invalid permissions</Error>`)
`ugc/get` -> <Failure/>
`account/register` -> signedUpKabamEmail (0 or 1), name, guid is one int from this list: https://pastebin.com/2nZcxNq5. using it you can create accounts with specific name
`account/v` -> action is always `I swear to Oryx I am no bot`
`account/saveSecurityQuestions` -> guid, password, answers (string encoded in base64 and contains three answers splitted by `|`)
`account/purchasePackage` -> guid, password, boxId, quantity, price, currency
`account/purchaseMysteryBox` -> guid, password, boxId, quantity, price, currency
`fame/list` -> gameClientVersion is no longer used
`guild/listMembers` -> num, offset
`supportCampaign/create`
`sfx` -> may be leave this link? https://realmofthemadgod.fandom.com/wiki/Sounds
`guild/purchase` (WTF) -> <Failure/>
`log/logFteStep` -> game_net_user_id, game_net, play_platform, guid, password, fteStepCompleted (used for tracking tutorial progress)
![what can fteStepCompleted accept](https://user-images.githubusercontent.com/42045258/58372711-2b1a2b00-7f2a-11e9-9329-1075d9e80022.png)

`data/ANY STRING` -> Go away, mortal . We have no use for your kind here.

**Params for old links (archive?)**
`steamworks/register` -> newGUID, newPassword, entrytag
`account/getBeginnerPackageTimeLeft` -> guid, password

**Comment by crinny** [comment]
For reference: Full-time equivalent (FTE) is used to measure a worker's or student's involvement in a project, or to track cost reductions in an organization

**Comment by Zeroeh** [comment]
Good finds! And thanks for the FTE explanation.

**Comment by crinny** [comment]
UPD on known url params:
`game_net`: kabam.com, kongregate, steam or rotmg depending on platform
`play_platform`: same as game_net

**Comment by crinny** [comment]
Hey, what about this issue? It is open for like 3 months

**Comment by Zeroeh** [comment]
I think I got most of em. If you didn't figure it out, guild/purchase is for upgrading the guild hall
