### ISSUE TITLE
New challenger mode specific stuff

### ISSUE THREAD

**Issue by crinny** [Zeroeh/RotMG-Appspot#13]
Only checked if working on https://test.realmofthemadgod.com/

* season/getSeasons => guid, password, gameClientVersion
```xml
<Seasons><Season title ="Public Testing Season"><Start>1567764000.0</Start><End>1568012400.0</End><Description>This is first season created for Public Testing.</Description><RequiredBestCharFame>0</RequiredBestCharFame><AccountCreatedBefore>1568073600.0</AccountCreatedBefore><MaxLives>9999</MaxLives></Season></Seasons>
```
* char/list => challenger (false or true)
* log/logGameModePlayed => seasonID (Public Testing Season), gameMode (Legacy or Challenger), guid, password
* fame/challengerLeaderboard => accountId, charId, timespan (same as fame/list)
* fame/challengerAccountLeaderboard => accountId, charId, timespan (same as fame/list)

**Comment by Zeroeh** [comment]
Nice finds! I think I'm going to wait until these are released on prod before adding them.

**Comment by crinny** [comment]
Now released on production servers

**Comment by Zeroeh** [comment]
Added
